POST http://localhost:3000/dev/enrich-email
Content-Type: application/json

{
  "email": "Carlina Lambert|carli.lambert@stinson.com"
}

###


POST http://localhost:3000/dev/enrich-email
Content-Type: application/json

{
  "email": "ssimao@fordharrison.com"
}

###


POST http://localhost:3000/dev/enrich-email
Content-Type: application/json

{
  "email": ["ben@geekinc.ca", "badamson@truegreencapital.com"],
  "format": "csv"
}

###
