service: apollo-search-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 10

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /api/search
          method: post
          cors: true
  apollo:
    handler: app.handler
    events:
      - http:
          path: /api/apollo
          method: get
          cors: true
  local-search:
    handler: app.handler
    events:
      - http:
          path: /api/local-search
          method: post
          cors: true
  local-upsert-query:
    handler: app.handler
    events:
      - http:
          path: /api/local-upsert-query
          method: post
          cors: true
