
service: apollo-search-api

plugins:
  - serverless-offline

useDotenv: true

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 10

functions:
  apollo:
    handler: app.handler
    events:
      - http:
          path: /api/apollo
          method: get
          cors: true
  armpit:
    handler: app.handler
    events:
      - http:
          path: /api/armpit
          method: get
          cors: true
  armpit2:
    handler: app.handler
    events:
      - http:
          path: /api/armpit/{count}
          method: get
          cors: true
  login:
    handler: app.handler
    events:
      - http:
          path: /api/login
          method: post
          cors: true
  logout:
    handler: app.handler
    events:
      - http:
          path: /api/logout
          method: post
          cors: true
  usersCount:
    handler: app.handler
    events:
      - http:
          path: /api/users/count
          method: get
          cors: true
