frameworkVersion: "3.34.0"

service: dynamic-sales-webhooks

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin


provider:
  name: aws
  runtime: nodejs16.x
  versionFunctions: true
  stage: ${opt:stage, "dev"}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:*
      Resource: "*"

functions:

  enrich-email:
    handler: functions/apollo/enrich-email.main
    timeout: 900
    events:
      - http:
          path: enrich-email
          method: post

  search-prospects:
    handler: functions/apollo/search-prospects.main
    timeout: 900
    events:
      - http:
          path: search-prospects
          method: post

  put-stored-profile:
    handler: functions/stored-profiles/put-stored-profile.main
    timeout: 900
    events:
      - http:
          path: stored-profile
          method: put

  post-stored-profile:
    handler: functions/stored-profiles/post-stored-profile.main
    timeout: 900
    events:
      - http:
          path: stored-profile
          method: post

  get-stored-profile:
    handler: functions/stored-profiles/get-stored-profile.main
    timeout: 900
    events:
      - http:
          path: stored-profile/{customer}
          method: get

  armpit:
    handler: functions/armpit.main
    events:
      - http:
          path: armpit/{count}
          method: get
