service: evrbed-api

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

useDotenv: true
provider:
  name: aws
  endpointType: edge
  versionFunctions: true
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "ca-central-1"}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:*
      Resource: "*"

functions:

  createCustomer:
    handler: functions/shopify/createCustomer.main
    events:
      - http:
          path: customer/create
          method: post
          cors: true

  queryCustomer:
    handler: functions/shopify/queryCustomer.main
    events:
      - http:
          path: customer/query
          method: get
          cors: true

  updateCustomer:
    handler: functions/shopify/updateMattressConfiguration.main
    events:
      - http:
          path: customer/mattressConfiguration/update
          method: post
          cors: true

  createCart:
    handler: functions/shopify/createCart.main
    events:
      - http:
          path: customer/cart/create
          method: post
          cors: true
