frameworkVersion: "3.25.1"

service: search-api-dynamic

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

useDotenv: true
provider:
  name: aws
  runtime: nodejs16.x
  versionFunctions: true
  stage: ${opt:stage, "dev"}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:*
      Resource: "*"

functions:

  armpit:
    handler: functions/armpit.main
    events:
      - http:
          path: armpit/{count}
          method: get
          cors: true
