service: search-api-dynamic

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

useDotenv: true
provider:
  name: aws
  endpointType: edge
  versionFunctions: true
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "ca-central-1"}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:*
      Resource: "*"

functions:

  armpit:
    handler: functions/armpit.main
    events:
      - http:
          path: armpit/{count}
          method: get
          cors: true
