# Really excellent example of how to create an S3 bucket with CORS configuration and an IAM role for uploading to the bucket
# The origin of this wisdom is: https://moduscreate.com/blog/upload-files-to-aws-s3-using-a-serverless-framework/

Resources:
  cdgsTemplatesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cdgs-templates
      AccessControl: Private
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
              - PUT
              - POST
              - HEAD
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
