Resources:
  UploadRole:             # TODO: - Determine why this is not allowing uploads on the deployed S3 bucket
    Type: AWS::IAM::Role  #       - The role is created, but the lambda function is not allowed to upload to the bucket
    Properties:           #       - Current fix is to make the bucket public
      RoleName: UploadRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: upload-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  !Sub
                  - "arn:aws:s3:::${BucketName}/*"
                  - {BucketName: !Ref cdgsTemplatesBucket}
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  Fn::Sub:
                    - arn:aws:logs:${Region}:${AccountId}:log-group:/aws/lambda/*:*:*
                    - { Region: !Ref AWS::Region, AccountId: !Ref AWS::AccountId }
