
Resources:
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cdgs-templates
      AccessControl: Private
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
              - PUT
              - POST
              - HEAD
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
